name: brianboyko/consoley
author:
  name: Brian Boyko
  email: brian.boyko@gmail.com
  url: 'http://brianboyko.github.io'
copyright: 2015 Brian Boyko
description: 'A simple, Ninite-like Javascript program that allows for users to click the Debian-based Apt-Get and other packages they would like on their Linux system and install them with just one line of console copy-and-paste'
